# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf

font_family Maple Mono Normal NF CN
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12
encoding utf-8
pango_markup yes
background_opacity 0.7
