# ~/.config/hypr/hypridle.conf
general {
    lock_cmd = hyprlock                     # 锁屏命令
    unlock_cmd = hyprctl dispatch dpms on   # 解锁时强制亮屏
    before_sleep_cmd = systemctl suspend    # 挂起前执行
    ignore_dbus_inhibit = false             # 允许应用抑制空闲（如视频播放器）
}

# 无操作 120 秒锁屏
listener {
    timeout = 120
    on-timeout = hyprlock
}

# 无操作 300 秒熄屏
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = nvidia-settings --load-config-only && hyprctl dispatch dpms on # 键盘/鼠标唤醒
}

# 无操作 1200 秒后挂起
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
